### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by HastingsGreer**

### CODE REVIEW

**Comment by HastingsGreer** [comment]
lgtm?

**Comment by HastingsGreer** [comment]
check out https://icon.readthedocs.io/en/doc-update/register_fives.html

**Comment by HastingsGreer** [comment]
@lintian-a does this look ok to merge to you? the only changes to the library itself are to allow cpu-training on machies that have a gpu, the rest is adding documentation

**Review by thewtex — COMMENTED** [review]
Nice~!

**Review by lintian-a — APPROVED** [review]

**Pull request merged**
